name: flutter_image
version: 0.0.1
description: >
  Image utilities for Flutter: providers, effects, etc
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter_image

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  test: any
