name: multicast_dns_examples
description: Example package for mDNS queries (e.g. Bonjour, Avahi).
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/packages/tree/master/packages/mdns
publish_to: none

dependencies:
  args: ^1.5.0 
  multicast_dns:
    path: ../

environment:
  sdk: ">=2.1.0-dev.7.1 <3.0.0"

