name: metrics_center
description:
  Support multiple performance metrics sources/formats and destinations.
repository: https://github.com/flutter/packages/tree/master/packages/metrics_center
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+metrics_center%22
version: 0.1.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  equatable: ^1.2.5
  gcloud: ^0.7.3
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  http: ^0.12.2

dev_dependencies:
  fake_async: ^1.2.0-nullsafety.3
  mockito: ^4.1.1
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.9
