name: flutter_markdown
description: A markdown renderer for Flutter.
version: 0.1.0
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io

dependencies:
  flutter:
    path: ../flutter
  markdown: '^0.9.0'
  string_scanner: '^0.1.5'

dev_dependencies:
  flutter_test:
    path: ../flutter_test
