name: css_colors
description: Defines constants for the CSS Colors
repository: https://github.com/flutter/packages/tree/master/packages/css_colors
version: 1.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
