name: css_colors
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Defines constants for the CSS Colors
homepage: https://github.com/flutter/css_colors
version: 1.1.0

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter
