name: flutter_lints
description: Recommended lints for Flutter apps, packages, and plugins.
version: 1.0.0-dev.0
homepage: https://github.com/flutter/packages/tree/master/packages/flutter_lints

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lints: ^1.0.0-dev.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
