name: image_colors
description: A simple example of how to use the PaletteGenerator to load the palette from an image file.

version: 0.1.0

publish_to: none

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  palette_generator:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/landscape.png

environment:
  sdk: ">=2.2.0 <3.0.0"
